services:
  auth_service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./auth/app:/app
    env_file:
      - ./auth/.env
    restart: unless-stopped

  users_service:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./users/app:/app
    env_file:
      - ./users/.env
    restart: unless-stopped
